services:
  alloy:
    build:
      context: ./alloy
      dockerfile: Dockerfile
    container_name: alloy
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "9090:9090" # Alloy's own metrics/debug UI
    environment:
      - GRAFANA_CLOUD_LOKI_ENDPOINT=${GRAFANA_CLOUD_LOKI_ENDPOINT}
      - GRAFANA_CLOUD_LOKI_USERNAME=${GRAFANA_CLOUD_LOKI_USERNAME}
      - GRAFANA_CLOUD_LOKI_PASSWORD=${GRAFANA_CLOUD_LOKI_PASSWORD}
      - GRAFANA_CLOUD_PROM_ENDPOINT=${GRAFANA_CLOUD_LOKI_ENDPOINT}
      - GRAFANA_CLOUD_PROM_USERNAME=${GRAFANA_CLOUD_PROM_USERNAME}
      - GRAFANA_CLOUD_PROM_PASSWORD=${GRAFANA_CLOUD_PROM_PASSWORD}
      - GRAFANA_CLOUD_TEMPO_ENDPOINT=${GRAFANA_CLOUD_TEMPO_ENDPOINT}
      - GRAFANA_CLOUD_TEMPO_USERNAME=${GRAFANA_CLOUD_TEMPO_USERNAME}
      - GRAFANA_CLOUD_TEMPO_PASSWORD=${GRAFANA_CLOUD_TEMPO_PASSWORD}
      - POSTGRES_DSN=${POSTGRES_DSN}
    networks:
      - coolify
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/postgresql:/var/log/postgresql:ro
      - /proc:/host/proc:ro # Map host's /proc to /host/proc in container
      - /sys:/host/sys:ro   # Map host's /sys to /host/sys in container
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro

    labels:
      - coolify.managed=true
      - coolify.applicationId=17
      - coolify.type=application
    privileged: true # This is often necessary for full host visibility via exporter.unix and journal.
networks:
  coolify:
    external: true
