services:
  alloy:
    build:
      context: ./alloy
      dockerfile: Dockerfile
    container_name: alloy
    command: run /etc/alloy/config.alloy --stability.level=experimental --server.http.listen-addr=0.0.0.0:9090
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "9090:9090" # Alloy's own metrics/debug UI
    environment:
      - GRAFANA_CLOUD_LOKI_ENDPOINT=${GRAFANA_CLOUD_LOKI_ENDPOINT}
      - GRAFANA_CLOUD_LOKI_USERNAME=${GRAFANA_CLOUD_LOKI_USERNAME}
      - GRAFANA_CLOUD_LOKI_PASSWORD=${GRAFANA_CLOUD_LOKI_PASSWORD}
      - GRAFANA_CLOUD_PROM_ENDPOINT=${GRAFANA_CLOUD_PROM_ENDPOINT}
      - GRAFANA_CLOUD_PROM_USERNAME=${GRAFANA_CLOUD_PROM_USERNAME}
      - GRAFANA_CLOUD_PROM_PASSWORD=${GRAFANA_CLOUD_PROM_PASSWORD}
      - GRAFANA_CLOUD_TEMPO_ENDPOINT=${GRAFANA_CLOUD_TEMPO_ENDPOINT}
      - GRAFANA_CLOUD_TEMPO_USERNAME=${GRAFANA_CLOUD_TEMPO_USERNAME}
      - GRAFANA_CLOUD_TEMPO_PASSWORD=${GRAFANA_CLOUD_TEMPO_PASSWORD}
      - GRAFANA_CLOUD_PYRO_ENDPOINT=${GRAFANA_CLOUD_PYRO_ENDPOINT}
      - GRAFANA_CLOUD_PYRO_USERNAME=${GRAFANA_CLOUD_PYRO_USERNAME}
      - GRAFANA_CLOUD_PYRO_PASSWORD=${GRAFANA_CLOUD_PYRO_PASSWORD}
      - POSTGRES_DSN=${POSTGRES_DSN}
    networks:
      - coolify
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/postgresql:/var/log/postgresql:ro
      - /proc:/host/proc:ro # Map host's /proc to /host/proc in container
      - /sys:/host/sys:ro   # Map host's /sys to /host/sys in container
      - /var/log/journal:/var/log/journal:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro

    labels:
      - coolify.managed=true
      - coolify.applicationId=17
      - coolify.type=application
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.alloy-router.rule=Host(`alloy.rtglabs.net`)" # Your desired domain
      - "traefik.http.routers.alloy-router.entrypoints=http,https" # Allow access via HTTP and HTTPS
      - "traefik.http.routers.alloy-router.tls.certresolver=letsencrypt" # Use Coolify's configured Let's Encrypt resolver for HTTPS
      - "traefik.http.services.alloy-service.loadbalancer.server.port=9090" # The internal container port Alloy's UI listens on
      # Optional: Redirect HTTP to HTTPS
      - "traefik.http.routers.alloy-router-http.rule=Host(`alloy.rtglabs.net`)"
      - "traefik.http.routers.alloy-router-http.entrypoints=http"
      - "traefik.http.routers.alloy-router-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    privileged: true # This is often necessary for full host visibility via exporter.unix and journal.
networks:
  coolify:
    external: true
